channels:
  - conda-forge
  - nodefaults

dependencies:
  # run deps
  - doit
  - pip
  - python >=3.8,<3.12
  - tomli
  # run deps
  # optional deps
  - jinja2
  - json-e
  - jsonschema-with-format
  - pyyaml
  # optional deps
  # build deps
  - flit >=3.8
  - jsonschema-gentypes
  # build deps
  # publish deps
  - twine
  # publish deps
  # lint deps
  - black
  - mypy
  - nbqa
  - nbstripout
  - nodejs >=18,<19
  - ruff
  - ssort
  - taplo
  - types-jinja2
  - types-jsonschema
  - types-pyyaml
  - yarn >=3,<4
  # lint deps
  # test deps
  - pytest
  - pytest-console-scripts
  - pytest-cov
  - pytest-html
  - pytest-json-report
  - pytest-xdist
  - tomli-w
  - python-build
  # test deps
  # demo deps
  - ipylab
  - ipywidgets >=8
  - jupyterlab >=3.6.3,<4
  - jupyterlab-markup
  # demo deps
  # docs deps
  - docutils >=0.19
  - jupyterlite-pyodide-kernel
  - jupyterlite-core-with-libarchive
  - myst-nb
  - pydata-sphinx-theme
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinx-design
  - sphinx-jsonschema
  - sphinxcontrib-mermaid
  - importnb
  - scour
  # docs deps
  # check deps
  - pytest-check-links
  # check deps

name: doitoml-demo
