channels:
  - conda-forge
  - nodefaults

dependencies:
  # run deps
  - doit
  - pip
  - python >=3.8,<3.12
  - tomli
  # run deps
  # optional deps
  - jinja2
  - json-e
  - jsonschema-with-format
  - pyyaml
  # optional deps
  # build deps
  - flit >=3.8
  - jsonschema-gentypes
  - taplo
  # build deps
  # demo deps
  - ipylab
  - ipywidgets >=8
  - jupyterlab >=4,<5
  # demo deps
  # docs deps
  - docutils >=0.19
  - jupyterlite-pyodide-kernel
  - jupyterlite-core-with-libarchive
  - myst-nb
  - pydata-sphinx-theme
  - sphinx-autobuild
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinx-design
  - sphinx-jsonschema
  - sphinxcontrib-mermaid
  - importnb
  - scour
  # docs deps

name: doitoml-docs
